spring:
  application:
    name: sicredi_teste
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
app:
  sicredi:
    url: ${BASE_URL:http://localhost:8080}
